services:
  - type: web
    name: campusblooddonor
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT --timeout 120 --workers 2 --threads 2 app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: SENDGRID_API_KEY
        sync: false  # You'll need to add this in Render dashboard
      - key: FROM_EMAIL
        value: abhip141003@gmail.com
